[default.probe]
protocol = "Swd"

[default.flashing]
enabled = true

[default.reset]
enabled = true
halt_afterwards = false

[default.general]
chip = "nRF52840_xxAA"
chip_descriptions = []

[default.rtt]
enabled = true
up_channels = [
    { channel = 0, name = "main", up_mode = "BlockIfFull", format = "Defmt" },
]

[default.gdb]
enabled = false

# RTT only configuration

[rtt.reset]
enabled = true

[rtt.flashing]
enabled = false

[rtt.rtt]
enabled = true
